[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.76"
wasm-bindgen = "0.2.63"
web-sys = { version = "0.3.76", features = ["console", "ImageData"] }

[lib]
crate-type = ["cdylib", "rlib"]
